version: '3'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: jitsi/etherpad
        environment:
            - PUBLIC_URL
        networks:
            meet.jitsi:
